# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: PIE | Playful Interactive Environments
email: pie@fh-hagenberg.at
description: Playful Interactive Environments is a research group founded by the Department of Digital Media at the University of Applied Sciences Upper Austria, School of Informatics, Communication and Media in Hagenberg.
baseurl: "/pie.fh-hagenberg.at" # the subpath of your site, e.g. /blog
#url: "http://pie.fh-hagenberg.at" # the base hostname & protocol for your site
url: "http://playful-interactive-environments.github.io" # the base hostname & protocol for your site
facebook: playful.interactive.environments

# Build settings
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "" #disable excerpts

exclude: [
  "package.json",
  "node_modules",
  "gulpfile"
]

gems:
  - jekyll-feed
  - jekyll-sitemap

collections:
  pages:
    output: true
  projects:
    output: true
    permalink: /projects/:path/

defaults:
  - scope:
      type: projects
    values:
      layout: project
